sudo: false

language: bash

os:
  - linux

before_script:
  - "export DISPLAY=:99.0"
  - sleep 3 # give xvfb some time to start
  - wget http://downloads.arduino.cc/arduino-1.8.5-linux64.tar.xz
  - tar xf arduino-1.8.5-linux64.tar.xz
  - mv arduino-1.8.5 $HOME/arduino_ide
  - cd $HOME/arduino_ide/hardware
  - mkdir esp32
  - cd esp32
  - git clone https://github.com/espressif/arduino-esp32.git esp32
  - cd esp32/tools
  - python get.py
  - cd ..
  - mv $TRAVIS_BUILD_DIR/libraries/ESP32SSDP $HOME/arduino_ide/libraries/
  - mv $TRAVIS_BUILD_DIR/libraries/arduinoWebSockets $HOME/arduino_ide/libraries/
  
script:
  - cd $TRAVIS_BUILD_DIR
  - source command.sh
  - export PATH="$HOME/arduino_ide:$PATH"
  - arduino --board esp32:esp32:esp32:PartitionScheme=min_spiffs,FlashFreq=40 --pref compiler.warning_level=all --save-prefs
  - sed -n '48,72p;73q' $TRAVIS_BUILD_DIR/Grbl_Esp32/config.h
  - sed -i "s/\/\/#define ENABLE_BLUETOOTH/#define ENABLE_BLUETOOTH/g" $TRAVIS_BUILD_DIR/Grbl_Esp32/config.h
  - sed -i "s/#define ENABLE_BLUETOOTH/\/\/#define ENABLE_BLUETOOTH/g" $TRAVIS_BUILD_DIR/Grbl_Esp32/config.h
  - sed -i "s/\/\/#define ENABLE_WIFI/#define ENABLE_WIFI/g" $TRAVIS_BUILD_DIR/Grbl_Esp32/config.h
  - sed -n '48,72p;73q' $TRAVIS_BUILD_DIR/Grbl_Esp32/config.h
  - build_sketch  $TRAVIS_BUILD_DIR/Grbl_Esp32/Grbl_Esp32.ino
  - sed -i "s/\/\/#define ENABLE_BLUETOOTH/#define ENABLE_BLUETOOTH/g" $TRAVIS_BUILD_DIR/Grbl_Esp32/config.h
  - sed -i "s/#define ENABLE_WIFI/\/\/#define ENABLE_WIFI/g" $TRAVIS_BUILD_DIR/Grbl_Esp32/config.h
  - sed -n '48,72p;73q' $TRAVIS_BUILD_DIR/Grbl_Esp32/config.h
  - build_sketch  $TRAVIS_BUILD_DIR/Grbl_Esp32/Grbl_Esp32.ino
  - sed -i "s/\/\/#define ENABLE_BLUETOOTH/#define ENABLE_BLUETOOTH/g" $TRAVIS_BUILD_DIR/Grbl_Esp32/config.h
  - sed -i "s/\/\/#define ENABLE_WIFI/#define ENABLE_WIFI/g" $TRAVIS_BUILD_DIR/Grbl_Esp32/config.h
  - sed -n '48,72p;73q' $TRAVIS_BUILD_DIR/Grbl_Esp32/config.h
  - build_sketch  $TRAVIS_BUILD_DIR/Grbl_Esp32/Grbl_Esp32.ino

  
notifications:
  email:
    on_success: change
    on_failure: change
